#!/usr/bin/env bash

NAME=listen4tunnel
DESC="AWS IoT Core Tunnel Listener"
DAEMON_BIN=/opt/listen4tunnel/listen4tunnel
DAEMON_PID=/var/run/$NAME.pid

function do_start {
    echo "Starting $NAME"
	start-stop-daemon \
        -S \
        --background \
        --make-pidfile \
        --pidfile $DAEMON_PID \
        --startas sh -- -c "exec $DAEMON_BIN >> /var/log/$NAME.log 2>&1"
}

function do_stop {
    echo "Stopping $NAME"
    start-stop-daemon \
        -K \
        --oknodo \
        --quiet \
        --pidfile $DAEMON_PID
}

case "$1" in
    "start")
        do_start
        ;;
    "stop")
        do_stop
        ;;
    "restart")
        do_stop
        do_start
        ;;
    *)
        echo "Usage: $1 {start|stop|restart}"
        exit 1
        ;;
esac
